---
name: Hash-Slice
version: 0.02
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
abstract: Make a hash from a deep slice of another hash
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
build_requires:
  Test::Deep: 0
  Test::More: 0
recommends:
  Clone: 0
  Storable: 0
provides:
  Hash::Slice:
    file: lib/Hash/Slice.pm
    version: 0.02
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
